### ISSUE TITLE
isTabVisible prevents chart being rendered

### ISSUE THREAD

**Issue by adamxi** [c3js/c3#2533] opened 2018-11-22 11:27 UTC
When a chart finishes its rendering in a tab that is currently not visible, all plots of the charts is not rendered when the tab becomes visible again.
As a temporary fix i changed the **ChartInternal.prototype.isTabVisible** method to always return true.

* **C3 version**:
0.6.8
* **D3 version**:
5.7.0
* **Browser**:
Chrome(latest)/IE11
* **OS**:
Windows

**Comment by kt3k** [comment] 2018-11-25 06:46
This should be fixed in v0.6.9. Please reopen this if the issue is still remaining.

**Comment by benjaminrigaud** [comment] 2018-11-29 13:01
I don't know if is related: but I have huge performance issues (Tab freezing & high cpu & memory usage after a while) on the 0.6.9 (compared to 0.6.8)  and still a few charts are not rendering properly at first.

When the chart is not rendered: it generates `Uncaught INDEX_SIZE_ERR` errors on hover.

**Comment by panthony** [comment] 2019-08-08 12:13
@kt3k I confirm that the charts won't draw if the tab is hidden. It was broken by f4a163f7128ed9218265ed9ce5163d758d604302 where `isTabVisible` wrap the whole logic of drawing, with or without animation.

**Closed** 2019-08-09 06:16 UTC
