### ISSUE TITLE
y2 axis ticks display wrong values 

### ISSUE THREAD

**Issue by 001balance** [c3js/c3#1917] opened 2016-12-28 14:53 UTC
Hello,
I'm associating data to both y and y2 
```
data{
axes:{
data1 : "y"
data2 : "y2"
}}
```
data1 and data2 have almost the same scale, however while the ticks of y show the right values with the right range, y2 only works with very small data values but when the data values are big (300, 258 ...), y2 ticks show respectively : 0,5,1,1,2,2,3,3 .
I also use `tick : {format: d3.format("d")} `which seems only to work when the values of data are very small .

Any idea why this is happening ?
Any help would be appreciated.
Thanks

**Comment by panthony** [comment] 2019-08-12 10:03
Closing as I cannot reproduce:

http://jsfiddle.net/j2fLd0q6/

**Closed by panthony** 2019-08-12 10:03 UTC
