### ISSUE TITLE
Using toString as a data title causes c3 to crash (C3 0.4.11)

### ISSUE THREAD

**Issue by bobjrsenior** [c3js/c3#1816] opened 2016-08-25 19:55 UTC
C3 Version: 0.4.11
Using toString as a data title causes c3 to crash. I tested this in Chrome, Firefox, and internet explorer 11.

With a Pie Chart, it gives the error: "Uncaught TypeError: t.indexOf is not a function"

Example:

``` Javascript
var chart = c3.generate({
    data: {
        columns: [
            ['toString', 30]
        ],
        type : 'pie',
    }
});
```

With a  line chart, it silently fails.

Example:

``` Javascript
var chart = c3.generate({
    data: {
        columns: [
            ['toString', 30, 50]
        ]
    }
});
```

**Comment by panthony** [comment] 2018-03-25 08:56
Closing as duplicate of #662

**Closed by panthony** 2018-03-25 08:56 UTC
