### ISSUE TITLE
Wrong Rendering

### ISSUE THREAD

**Issue by paolog22** [c3js/c3#2465] opened 2018-08-27 04:55 UTC
here is the sample 
![image](https://user-images.githubusercontent.com/12680745/44641188-57833400-a9f8-11e8-8132-189ab1ec0b57.png)

* **C3 version**:
* **D3 version**: 
* **Browser**: 
* **OS**:

**Comment by paolog22** [comment] 2018-09-19 03:40
@kt3k

**Comment by kt3k** [comment] 2018-09-19 06:52
@paolog22 
I don't get what is wrong about the above. `Tricare` has a huge value compared to other values, and it seems rounded to 100%.

**Comment by paolog22** [comment] 2018-09-19 09:31
but it doest show the other values it suppose show tricare has the bigger cut but it became 100%

**Comment by panthony** [comment] 2018-10-20 10:09
It shows the other values because they are not 0.

You can pass `donut.label.format` if you want the % value with a better precision (ex: 99.99998%).

A better alternative may be that you regroup the small outliers in a single category before passing it to c3js.

There is already an issue opened for have this as an opt-in for c3js (#868).

Closing as not a bug.

**Closed by panthony** 2018-10-20 10:09 UTC
