### ISSUE TITLE
Tooltip broken on donut chart for latest version of c3.js ?

### ISSUE THREAD

**Issue by emiliepicardcantin** [c3js/c3#2373] opened 2018-05-22 19:37 UTC
* **C3 version**: 0.6.1
* **D3 version**: 4.13
* **Browser**: Chrome (Version 66.0.3359.181 )
* **OS**: Windows 10

As I understand it, the `c3.js` tooltip worked fine with the the `3.5.6` version of `d3.js` and the `0.4.11` of `c3.js`. 
[Here is an example of the working tooltip.](https://jsfiddle.net/emiliepicardcantin/8zsbn3z4/)

Unfortunately, I am working with the `4.13` version of `d3.js`. I believe this requires at least the `0.5.0` version of `c3.js`. I have tested with a few version from `0.5.4` to `0.6.1` without sucess.

Here is an [example](https://jsfiddle.net/emiliepicardcantin/1v0vm88w/) with the most recent versions of `c3.js` and `d3.js`. As you can see, the tooltip does not show.

Is the tooltip broken for the donut chart ? Is there a workaround that I can use ?

**Comment by prtome** [comment] 2018-05-25 08:50
Hello, I have the exact same problem, same versions from cdnjs
  here is my example https://codepen.io/prtome/pen/LmKPpy

**Comment by panthony** [comment] 2018-05-25 08:50
Hi @emiliepicardcantin , could it be a duplicate of #2354 ?

Did you try the suggested workaround?

**Comment by prtome** [comment] 2018-05-25 08:52
hi @panthony - right for me it works when adding the solution in #2354 to css
Thanks

**Comment by emiliepicardcantin** [comment] 2018-05-29 14:10
Hi @panthony ! Thanks for the link, it did work for me. I didn't find this solution when I did my research, sorry.

**Comment by panthony** [comment] 2018-05-29 14:26
@emiliepicardcantin No worries, I close this issue as duplicate then :)

**Closed by panthony** 2018-05-29 14:26 UTC
