### ISSUE TITLE
Onclick is called multiple times(once per each datapoint) instead one

### ISSUE THREAD

**Issue by eugeneJava** [c3js/c3#1958] opened 2017-02-09 10:28 UTC
I have a setup:

var chart = c3.generate({
     "data":{ 
       "onclick" : function(d) {
           console.log(d.name);
       }   ,  
         
      "order":null,
      "columns":[  
         [  
            "SENSUM_IND", null, 49.0
         ],
         [  
            "VASGEN", 100.0, null
         ]
      ],
      "type":"line",
      "colors":{  
         "SENSUM_IND":"#ef87fe",
         "VASGEN":"#b1222c"
      },
      "groups":[  
         [  
            "SENSUM_IND",
            "VASGEN"
         ]
      ]
   },
   "size":{  
      "width":null,
      "height":null
   },
   "grid":{  
      "x":{  
         "lines":[  
            {  
               "value":"08-02-2017",
               "class":"dashed"
            },
            {  
               "value":"09-02-2017",
               "class":"dashed"
            }
         ]
      },
      "y":{  
         "show":true
      }
   },
   "axis":{  
      "x":{  
         "type":"category",
         "categories":[  
            "08-02-2017",
            "09-02-2017"
         ]
      },
      "rotated":false,
      "y":{  
         "tick":{  
            "values":[  
               0.0,
               10.0,
               20.0,
               30.0,
               40.0,
               50.0,
               60.0,
               70.0,
               80.0,
               90.0,
               100.0
            ]
         },
         "padding":{  
            "top":0
         }
      }
   },
   "title":{  
      "text":""
   },
   "legend":{  
      "show":true
   },
   "tooltip":{  
      "show":true
   },
   "padding":{  

   }
});

and by clicking on each datapoint - onclick is called multiple times instead of one. Please help. It seems an issue. Thanks

**Comment by schwassj** [comment] 2017-03-03 02:39
onclick seems to be driven by the x-value of the click, instead of the actual element clicked. I'm investigating this presently, but given #1965 it's unlikely any fix will be incorporated in the library. I'll post back if I find anything productive.

**Comment by panthony** [comment] 2017-07-10 14:47
Duplicate of #1658 ?

**Comment by panthony** [comment] 2018-03-25 08:19
closing as duplicate

**Closed by panthony** 2018-03-25 08:19 UTC
