### ISSUE TITLE
On Resize issue

### ISSUE THREAD

**Issue by vbala93** [c3js/c3#1783] opened 2016-07-28 14:57 UTC
on resize of window c3.js chart overlap its normal width of div.
on reload of window its looking fine.

![screen shot 2016-07-28 at 2 06 47 pm](https://cloud.githubusercontent.com/assets/3308352/17206280/956fccc0-54cc-11e6-9505-c4ab74970bdd.png)

Following code i have used:

var splinechart = c3.generate({
                size: {
                    height: 220,
                },
                bindto: '#fd_chart2',

```
            padding: {
                top: 10,
                right: 15,
                bottom: 0,
                left: 40,
            },
            data: {
                transition: {
                    duration: 20000
                },
                columns: [
                ['Tx', 300, 350, 300, 0, 0, 0,200],
                ['Rx', 130, 100, 140, 200, 150, 50,300],


                ],
                types: {
                    Tx: 'area-spline',
                    Rx: 'area-spline',


                },
                colors: {
                    Tx: '#5cd293',
                    Rx: '#1a78dd',

                },

            },
            tooltip: {
                show: false
            },
            point: {
                show: false
            },
            axis: {
                x: {
                    type: 'category',
                    padding: {
                        left: -0.5,
                        right: -0.5,
                    },
                    categories: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],

                },
                y: {
                    padding: {bottom: 0},
                    min: 0,
                    tick: {
                        format: d3.format("s")
                    }
                },
            }


        });
```

**Comment by kt3k** [comment] 2017-09-22 11:53
duplicate of #1782

**Closed by kt3k** 2017-09-22 11:53 UTC
