### ISSUE TITLE
null values drops data point

### ISSUE THREAD

**Issue by nitmpez** [c3js/c3#2629] opened 2019-06-07 18:48 UTC
Having issue with null values in charts.  As an example, I have the following chart code.  For some reason, for each null value you lose a data point at the end of the series.

var chart = c3.generate({
    data: {
        xs: {
            "d1": "d1_x",
            "d2": "d2_x",
            "d1Avg" : "d1Avg_x",
            "d2Avg" : "d2Avg_x"
        },
        rows: [
            [ 'd1', 'd1_x', 'd2', 'd2_x', 'd1Avg', 'd1Avg_x', 'd2Avg', 'd2Avg_x' ],
           
                [ null, null, null, null, null, null, null, null ],
           
                [ -2.46, -6.24, null, null, null, null, null, null ],
           
                [ 4.09, -0.29, 4.84, -4.19, null, null, null, null ],
           
                [ -2.97, -5.98, 1.97, -1.74, null, null, null, null ],
           
                [ -0.46, -7.15, -0.45, -0.01, -0.45, -4.71, 1.19, -2.64 ]
        ],
        type: 'line',
        xSort: false
    },
    color:{
        pattern: [ '#ff0000', '#3399ff' ]
    },
    grid: {
        x: {
            show: true,
            lines: [
                {value: 0, class: 'c3_line_axis'}
            ]
        },
        y: {
            show: true,
            lines: [
                {value: 0, class: 'c3_line_axis'}
            ]
        }
    },
    axis:{
        x: {
            tick: {
                fit: false
            },
            max: 7.2,
            min: -7.2
        },
        y: {
            max: 7.2,
            min: -7.2
        }
    },
    title: {
        text: 'Boggle'
    }
});

**Comment by panthony** [comment] 2019-08-09 13:37
I'm going to close this as duplicate of #1993

**Closed by panthony** 2019-08-09 13:37 UTC
