### ISSUE TITLE
Pie chart with multiple category

### ISSUE THREAD

**Issue by sanjayksuthar** [c3js/c3#2592] opened 2019-03-28 06:56 UTC
Hi,

I'm using c3 to draw charts, simple charts with 2-3 data set working fine but I need some more advance like category and subcategory.
I need output as an attached image.

![image](https://user-images.githubusercontent.com/48720204/55136537-aa6ec680-5154-11e9-9ef3-c909574c8d2f.png)

Thanks

**Comment by sanjayksuthar** [comment] 2019-03-28 06:57
Is there any option by this we can draw this type of chart?

**Comment by panthony** [comment] 2019-07-30 08:52
No, there is not an option to draw this kind of chart within c3js at the moment.
 
Closing as duplicate of #1133

**Closed by panthony** 2019-07-30 08:52 UTC
