### ISSUE TITLE
How to place labels texts(.c3-chart-texts)?

### ISSUE THREAD

**Issue by manking99** [c3js/c3#1774] opened 2016-07-19 08:27 UTC
Hello! How to place labels text to another place?

I try to change margin, top left to this css classes:
.c3-chart-texts
.c3-text c3-text-0
.c3-text c3-text-1

Example:
http://storage9.static.itmages.ru/i/16/0719/h_1468916833_3268381_900ef9ba65.png

like this:
http://storage9.static.itmages.ru/i/16/0719/h_1468916833_8376616_1f7fe36866.png

**Comment by panthony** [comment] 2016-08-23 13:44
This is not possible at the moment.

And I think you can close this ticket since it's a duplicate of #1670 .

I might take a look in a not so far distant future since I'll probably need it.

**Closed** 2018-03-24 10:25 UTC
