### ISSUE TITLE
x axis ticks text overlapping

### ISSUE THREAD

**Issue by sheshnathverma** [c3js/c3#2677] opened 2019-08-12 10:58 UTC
I'm using c3js for stack chart and I have also configure multiline but if words are long then its  overlapping to others x axis ticks label.

axis: {
                x: {
                    tick: {
                        type: 'category',
                        culling: false,
                        fit: true,
                        multiline: true,
                        multilineMax: 2                       
                }
            }

I have tried to add padding, margin but its does not work because ticks are svg tspan element.

![image](https://user-images.githubusercontent.com/10703169/62860383-a9ae8980-bd1d-11e9-8834-46036ed00e52.png)

**Comment by SpyTec** [comment] 2019-08-12 12:26
Hi,

I've gotten around this by rotating the ticks:

```
axis: {
  x: {
    type: 'category',
    categories: this.chartingData.categories,
    tick: {
      rotate: 60,
      multiline: false,
      fit: false
    }
  }
},
```

**Comment by panthony** [comment] 2019-08-12 15:19
Closing this issue as duplicate of #1078

**Closed by panthony** 2019-08-12 15:19 UTC
