### ISSUE TITLE
Placeholder in timeseries graph

### ISSUE THREAD

**Issue by what-is-a-crow** [c3js/c3#1092] opened 2015-03-31 16:37 UTC
We have a number of simple graphs throughout our app that will often have no data (they're displaying recent activity on what may very well be an inactive object). Our design team wanted to have a nicer empty state, so we currently just chuck a background image behind our graphs:

![screen shot 2015-03-31 at 12 34 30 pm](https://cloud.githubusercontent.com/assets/498191/6923903/9cdea9ca-d7a2-11e4-8164-b84c4d3f14a8.png)

This is obviously brittle and just not ideal. I would love to see some other way to set a placeholder or to set some sort of visual minimum for timeseries graphs.

**Comment by pchaganti** [comment] 2016-09-15 00:02
👍

**Comment by panthony** [comment] 2018-03-31 11:03
Closing because this is not a bug to fix and the description is too vague for a requested feature. Plus, not much traction after +3 years.

**Closed by panthony** 2018-03-31 11:03 UTC
