### ISSUE TITLE
Tooltip bug on zoom-drag

### ISSUE THREAD

**Issue by ppKrauss** [c3js/c3#2637] opened 2019-07-05 13:24 UTC
**Losing tooltip** bug.   <br/>The option `zoom:{enabled:true,type:'drag'}` is in conflict with `tooltip:{show:true}`.

Simple test: at the zoom-drag illustrated by [this sample](https://c3js.org/samples/interaction_zoom_by_drag.html), you can add `tooltip` option in it.

------

* **C3 version**: 0.7.1
* **D3 version**: 5.9.7
* **Browser**: Firefox v64.0
* **OS**: Windows v10

**Comment by panda-blue** [comment] 2019-07-10 09:26
cf: https://github.com/c3js/c3/issues/2501

**Comment by ppKrauss** [comment] 2019-07-10 17:16
Hi @panda-blue, thanks.  Yes seems the same problem... Close here?

**Comment by panthony** [comment] 2019-08-02 08:28
Duplicate of #2501

**Closed by panthony** 2019-08-02 08:28 UTC
