### ISSUE TITLE
hierarchical chart

### ISSUE THREAD

**Issue by karvannan-thi** [c3js/c3#2117] opened 2017-07-25 10:39 UTC
Any plan implement hierarchical chart like treemap, tree and sunbrust chart

**Comment by vcvreddy** [comment] 2017-08-30 10:46
HI  i am also looking for these some kind of charts like bubble heat map etc. which are already available in d3js. i have done the samples for these charts but how can i integrate these with c3js.

**Comment by dhvsandeep** [comment] 2018-03-29 08:37
Treemap(most likely sankey chart), Heatmap, bubble will do a great job in showing data informatively and intuitively.

Looking forward for these charts in C3.

**Comment by panthony** [comment] 2018-03-29 08:46
Closing as duplicate of #1200 #966 #212 ...

Also, please if a type of chart is required, create 1 issue per type of chart :)

**Closed by panthony** 2018-03-29 08:46 UTC
