### ISSUE TITLE
Hover over entire chart to show tooltip

### ISSUE THREAD

**Issue by kaspar-allenbach** [c3js/c3#2391] opened 2018-06-12 14:22 UTC
* **C3 version**: 0.5.4
* **D3 version**: 5.2.0
* **Browser**: FF
* **OS**: MacOS

I think the [Google Group is dead](https://groups.google.com/forum/#!topic/c3js/VC2hKY44h1Q). Right?

I have an [older c3 instance][1] where you can hover over the chart and the tooltip is showing no matter where you point at on the chart.

In a [newer instance][2] this behaviour is gone.

Now the tooltip is only shown when hitting the datapoint excately.

Is there a option for this?

  [1]: https://aare.guru/aare-statistiken
  [2]: http://c3js.org/samples/timeseries.html

**Comment by sebzap** [comment] 2018-07-04 13:33
I also need this functionality. Hover should display tooltip for nearest data point.

Can we get an option for this?

The workaround mentioned in the google groupe (increasing `chart.internal.config.point_sensitivity`) just makes the UX even worse when there are many data points close to each other.

**Comment by panthony** [comment] 2018-07-05 20:35
Closing as duplicate of #2362

**Closed by panthony** 2018-07-05 20:35 UTC
