### ISSUE TITLE
Repeatedly calling c3.generate leaks memory in 0.4.9

### ISSUE THREAD

**Issue by ergo** [c3js/c3#926] opened 2015-01-21 10:01 UTC
Hello,

I got reports that pages that constantly regenerate our chart objects use up too much memory and kill browser tabs:

http://plnkr.co/edit/l0JOvGBWRDEv0b3fwywr?p=preview - here is an example with 0.4.9 version

http://plnkr.co/edit/wEQiMgBeBzVAwYTdijKD?p=preview - here is an example with 0.4.8, it seems to leak way less and is way more stable according to my tests.

**Comment by aendrew** [comment] 2015-01-21 10:30
@ergo Interesting — is there any reason you're calling `destroy` and then loading more data instead of just using `api.load`?

**Comment by ergo** [comment] 2015-01-21 10:41
Yes, the reason is c3 doesn't support setting some options on load() - like changing chart types of existing series or setting new labels, or setting x tick values - this only works when generate() is called.
So my workaround is to just generate whole chart - not ideal but seems the only option right now when I will have generative charts and the values might change on update.

And yes I've tried downgrading to 3.5.0 and 3.4.3 - you can fork and edit the plunkers the 0.4.9 one will quickly reach 1.5gb mem regardless of d3 version used :(

**Comment by aendrew** [comment] 2015-01-21 10:59
@ergo Ah, I see — seemed like the data remained sort of constant, which was why I was wondering about `load()` (FWIW, I do the exact same thing with times/axisJS whenever the user changes chart types, would be really nice to be able to modify charts without having to call `c3.generate()` again. Might be worth creating a separate issue about improving `load()`'s functionality).

But yeah, tab just crashed again. Yikes, that's definitely an issue. Marking as bug.

**Comment by aendrew** [comment] 2015-01-22 12:17
There is definitely something leaking memory. I just tried to do a screencast using axisJS and it crashed the browser tab after about 2 minutes on my recent-model Macbook Pro. I'm going to investigate this today, this bug seems pretty dire...

**Comment by aendrew** [comment] 2015-01-22 14:41
I'll update this comment as I find more. In the meantime:
+ [Plunker](http://plnkr.co/edit/tWiBxCxPq2URD7Vpdwet)
+ Test code: ```
  var generateData = function() {
    var data = [];
    for (var i = 0; i < 5; i++) {
      var datum = [];
      datum.push('dataset ' + i);
      for (var j = 0; j < 20; j++) {
        datum.push(Math.random() * 1000);
      }
      data.push(datum);
    }

    return data;
  };

  var int;

  var toggleTest = function() {
    if (!int) {
      int = setInterval(function(){
        c3.generate({
          data: {
            columns: generateData()
          }
        });
      }, 3000);
    } else {
      clearInterval(int);
    }
  };
```
+ 10 minute heap snapshot [here](http://darkstar.aendrew.com/Heap-20150122T131329.heapsnapshot) (~230mb)

**Comment by aendrew** [comment] 2015-01-22 17:18
Actually, see [this comment on #172](https://github.com/masayuki0812/c3/issues/172#issuecomment-47257301). `generateResize()` comes up there too. 

Here's what I think is happening. `generateResize()` is attached to the `window` object, and all the resize functions keep getting pushed into the `resizeFunctions` array regardless of anything that happens with `generate()`. As a result, these functions hold references to expired SVG DOM elements, and these are never GC'd.

**Comment by masayuki0812** [comment] 2015-01-26 00:20
Thank you for the investigation. I also looked into this and noticed this seems to happen when the tab where the code running is not visible (Strictly speaking, still leaking, but it looks quite smaller).
Additionally, the PR @aendrew created #938 seems to fix this issue, so the transition when the tab is not visible might be the cause. And there are still some transitions even if we set `transition.duration = 0` or apply #938 , so I'll try to disable all of transitions.

**Comment by aendrew** [comment] 2015-01-26 11:08
@masayuki0812 Worth noting all the performance stuff I did was with the C3 chart tab active. I'm pretty sure it's a detached DOM nodes issue and not a requestAnimationFrame issue. AFAIK, the only way to fix this is to improve garbage collection, which is to empty `resizeFunctions` on `generate()` instead of just appending new functions to it.

**Comment by ergo** [comment] 2015-01-26 11:48
Agreed, i think the visibility should not impact the GC.

**Comment by snkashis** [comment] 2015-01-29 14:44
+1. Yes, @masayuki0812 I also noticed the `transition.duration = 0` disabling doesn't seem to work in all cases. Would another idea be some sort of global `c3.TRANSITIONS_ENABLED` switch so it doesn't need to be specified for each visualization? Able to be overridden though of course if needed...

**Comment by masayuki0812** [comment] 2015-02-10 00:58
@aendrew Yeah, I'm not saying #938 fixes the issue completely, it just makes the speed of leak slower as @ergo wrote in https://github.com/masayuki0812/c3/issues/926#issue-54998863 . Did you confirm it fixes this issue and can you create PR about this?

@snkashis can you create new issue? I expect it would be something like to disable all transitions.

**Comment by ergo** [comment] 2015-03-21 00:56
@masayuki0812 - Any news on this? I would love to update to latest stable but unfortunately have to wait till the leak is gone :)

**Comment by JamieMason** [comment] 2015-06-09 10:35
FYI we've just upgraded to 0.4.11-rc1 and have found the memory leak to be much less severe now. In our case we're calling `c3.generate(...)` once and then `.load(...)` on the returned instance — but c3 was leaking memory in our case as well.

![c3-memory](https://cloud.githubusercontent.com/assets/320492/8055941/7228c820-0e9b-11e5-80a0-a5381159d679.png)

**Comment by aendrew** [comment] 2015-06-09 11:03
@JamieMason Thanks for the update! The improved performance when using .load is due to #1113. Still need to squash this "calling generate repeated" bug though — so much of the C3 API is only exposed via .generate!

**Comment by chrismingay** [comment] 2015-06-18 15:25
Really appreciate your efforts with this. I just stumbled upon the memory leak updated `c3js-directive.js` so that in `loadChartData()` generate is only called once and after that the load() function is called.

```
if(!$scope.generated){
    console.log("This is the first load");
    $scope.chart = c3.generate($scope.config);    
    $scope.generated = true;
}else{
   $scope.chart.load($scope.config.data); 
}
```

I know this doesn't help for those who need to repeatedly generate() but it helped with my chart data stream needs!

**Comment by bwestpha** [comment] 2016-03-31 07:50
Any further news on this? I created a single page app with C3 charts and after all I implemented an auto-kiosk-slide mode, where all my diagrams were generated in a timer. .... the page crashes after about 2h of working. the javascript heap-size is full and I can confirm that generating new OR not properly deleting OLD diagrams causes a HUGE memory leak.

**Comment by ahalota** [comment] 2016-07-06 21:01
I'm having the same issues now where using c3.generate to make a few charts, removing the old ones (by removing DOM elements), and then creating new ones, it gets slower and slower.

@bwestpha How do I properly delete old diagrams?

**Comment by ahalota** [comment] 2016-07-06 21:05
I see now the method is called "destroy", I had been looking for remove or delete, I'll give that  a try.

**Comment by kelvinau** [comment] 2017-10-17 01:36
I found a temporary solution that can fix this memory issue. Just use the fallback code

            // fallback to this, if this is a very old browser
            var wrapper = window.onresize;
            if (!wrapper) {
                // create a wrapper that will call all charts
                wrapper = $$.generateResize();
            } else if (!wrapper.add || !wrapper.remove) {
                // there is already a handler registered, make sure we call it too
                wrapper = $$.generateResize();
                wrapper.add(window.onresize);
            }
            // add this graph to the wrapper, we will be removed if the user calls destroy
            wrapper.add($$.resizeFunction);
            window.onresize = wrapper;

instead at [https://github.com/c3js/c3/blob/fc6905129ebedde0968eb63097fc08531a843ee7/c3.js#L1989](url), and also use 

            var wrapper = window.onresize;
            // check if no one else removed our wrapper and remove our resizeFunction from it
            if (wrapper && wrapper.add && wrapper.remove) {
                wrapper.remove($$.resizeFunction);
            }

at [https://github.com/c3js/c3/blob/fc6905129ebedde0968eb63097fc08531a843ee7/c3.js#L3479](url)

My guess is window.removeEventListener is unable to remove the handler $$.resizeFunction because $$.generateResize returns a new instance of callResizeFunctions every time, and so addEventListener is not keeping the reference to the original callResizeFunctions

**Comment by kelvinau** [comment] 2017-10-17 23:17
Update:
the above fix will actually remove the feature of onresize & resized

destroy() can actually remove the event listeners, so that is not the problem.
My problem was because of Angular's issue. It tries to destroy the element before rendering it, and so the events binded to window are left and not destroyed. I just check if the element exists before rendering and it solves the memory issue.

**Comment by nazihahmed** [comment] 2018-01-29 09:15
hi, I have fixed all of the issues regarding the memory leak
https://github.com/c3js/c3/pull/2272
I use c3 heavily within an angular application until recently our clients started reporting browser crashing issues, I had 2 options either fix it or use a different library,
https://github.com/Aloomaio/c3

**Comment by nazihahmed** [comment] 2018-01-29 14:41
https://github.com/c3js/c3/pull/2273

**Comment by nazihahmed** [comment] 2018-01-29 14:42
note to make sure the memory leak doesn't happen you must call destroy

**Closed** 2018-02-10 08:24 UTC
Labels: bug, performance
