### ISSUE TITLE
以svg子标签g作为容器生成新的svg后鼠标移入无法显示当前坐标信息

### ISSUE THREAD

**Issue by yangdan8** [c3js/c3#2403] opened 2018-07-06 07:06 UTC
* **C3 version**:
* **D3 version**:
* **Browser**:
* **OS**:

**Comment by panthony** [comment] 2018-07-06 09:05
Thanks to google trad I'd say this is either a duplicate of #2362 or #2354.

If not, please feel free to reopen with a reproduction case using fiddlejs and a description in english 👍

**Closed by panthony** 2018-07-06 09:05 UTC
