### ISSUE TITLE
SvgPathSeg is removed in chrome 48

### ISSUE THREAD

**Issue by Karabur** [c3js/c3#1465] opened 2015-11-12 11:51 UTC
According to https://www.chromestatus.com/features#pathseg this interface was a part of svg1.1, but was removed.
Soon charts will be broken in chrome. 
And perhaps it will be removed from other browsers too. 
Library should use other way to avoid reference to pathSegList property.

**Comment by aendrew** [comment] 2015-11-12 13:22
Good catch, @Karabur!

This needs to be updated in the following places:

- [ ] [src/util.js][1]
- [ ] [src/shape.bar.js][2]

[1]: https://github.com/masayuki0812/c3/blob/931109f8269688b8d623b4523335670dd813b4dc/src/util.js#L43
[2]: https://github.com/masayuki0812/c3/blob/14b7f4ca4e91094d16458a83c5ce654c08287361/src/shape.bar.js#L117

**Comment by martingraham** [comment] 2015-11-13 11:18
Could this polyfill be bundled into c3? --> https://github.com/progers/pathseg

I suppose we could also add it individually to our projects in the meantime

**Comment by aendrew** [comment] 2015-11-13 12:30
@martingraham Ugh, would really like to not bundle another polyfill unless totally necessary. SvgPathSeg is only used three times in the entire codebase, would prefer just finding an alternative implementation.

**Comment by GerHobbelt** [comment] 2015-11-16 18:32
No polyfill required; the SVG path list is only used in a context where a straight bar block (rectangle) is expected (segment 0 and segment 1 are inspected in there to derive a corner coordinate); the above pullreq code keeps the existing code for those who still have SVG pathSegList support, while the alternative code works or Chrome Canary et al - at least it works for me. ;-)

**Comment by aendrew** [comment] 2015-11-16 21:02
@GerHobbelt You, good sir, are a gentleman and a scholar. :+1: :tada: 

Will review PR first opportunity. Many thanks!

**Comment by aendrew** [comment] 2015-12-01 12:34
Apologies for the delay, will try to get a chance to look at this this week.

**Comment by GerHobbelt** [comment] 2015-12-03 07:38
No worries. ;-)

**Comment by tracker-common** [comment] 2016-01-05 16:34
Hey @aendrew, just wanted to touch base and see if this bug is still in progress.

Thanks!

**Comment by bsarkadi** [comment] 2016-01-11 12:51
Hi @aendrew, I'd also like to ask when the fix for this is expected to be released. Thanks!

**Comment by Paulsky** [comment] 2016-01-21 13:54
Hello,

If anybody noticed; Chrome 48 was released yesterday: http://googlechromereleases.blogspot.be/2016/01/stable-channel-update_20.html. I've just updated Chrome, because I wanted to check if the click event (and my drilldown function) is still working. But, I can confirm that this does not work anymore.
I'd also would like to ask when a fix for this is going to be released. Thank you in advance!

**Comment by bottomline** [comment] 2016-01-22 10:14
We tried the other PR mentioned on this thread, but found it broke onclick handlers. We've instead created this PR: https://github.com/masayuki0812/c3/pull/1552

**Comment by onsamp** [comment] 2016-01-28 22:47
+1 SvgPathSeg is removed in chrome 48

**Comment by Sweterings** [comment] 2016-02-01 10:30
Are there any updates on this? It has been marked as "in progress", but it has been for nearly 2 months now.

**Comment by onsamp** [comment] 2016-02-01 15:36
We look forward error correction!

**Comment by rannmann** [comment] 2016-02-04 19:17
PR #1552 and #1564 both address this problem.  I haven't tested either since I don't have Chrome 48 yet.

Can anyone confirm their stability?

**Comment by LoneRifle** [comment] 2016-02-06 08:59
The gist for #1564 is known to work, since that involves dropping the referenced polyfill for the missing APIs (See comment 3 on this thread).

**Comment by smithd1** [comment] 2016-02-19 22:20
Hi, can anyone confirm that the #1564 fix works with Chrome 48?  So far my tests fail.  Thanks.

**Comment by aendrew** [comment] 2016-02-20 17:05
@smithd1 I just ran through the test suite in Chrome 48 using the current `HEAD` in the `dev` branch, so can confirm it works.

Will keep this issue open until the above fix is merged into `master`. It's a known working fix so we'll keep it, perhaps later replacing it with #1466 next release.

**Comment by smithd1** [comment] 2016-02-20 18:40
@aendrew Thanks so much for checking.  I discovered that I made a mistake on my end; it's working with Chrome 48 now.  Thanks again!

**Comment by masayuki0812** [comment] 2016-05-01 01:48
Thank you for working on this issue. I merged `dev` to the release branch `release/v.0.4.11`, then let mark `resolved maybe` and let close when it's released as anedrew said.

**Comment by masayuki0812** [comment] 2016-05-01 05:59
This has been merged into master and releases as 0.4.11. Thank you!

**Closed by masayuki0812** 2016-05-01 05:59 UTC
Labels: bug, in progress, resolved maybe
