### ISSUE TITLE
Click event triggers for more than one point, when points are closer to each other

### ISSUE THREAD

**Issue by joesamraj** [c3js/c3#2093] opened 2017-07-03 14:15 UTC
Hi,

`<html>
  <head>
    <link rel="stylesheet" type="text/css" href="c3.css"/>
  </head>
  <body>
    <div id="chart"></div>

    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="c3.js"></script>
    <script>
      var chart = c3.generate({
        data: {
          columns: [
            ['data1', 30, 200, 100, 400, 150, 250],
            ['data2', 50, 20, 10, 40, 15, 25],
			['data3', 55, 25, 30, 10, 25, 25],
			['data4', 50, 30, 40, 45, 25, 35]
          ],
          onclick: function (d, element) { console.log("onclick", d, element); },
          onmouseover: function (d) { console.log("onmouseover", d); },
          onmouseout: function (d) { console.log("onmouseout", d); },
        }
      });
    </script>
  </body>
</html>
`
  In the chart generated using the above code, if I click on point 30, then it triggers click event for all the points (30,50,55,50). Do you know any workaround or fix for it.

Regards,
Joe

**Comment by panthony** [comment] 2017-07-10 14:47
Duplicate of #1658 ?

**Comment by panthony** [comment] 2019-08-21 09:25
closing as duplicate

**Closed by panthony** 2019-08-21 09:25 UTC
