### ISSUE TITLE
Feature Request: Candlestick Charts 

### ISSUE THREAD

**Issue by MarcGodard** [c3js/c3#1680] opened 2016-05-02 15:34 UTC
Candlestick Charts would be an awesome add on.

**Comment by rszemplinski** [comment] 2017-09-07 16:35
+1

**Comment by larslue** [comment] 2017-09-12 16:36
+1 to this and looks like a duplicate of #121.

**Comment by hisham** [comment] 2018-01-16 18:09
+1

**Comment by cristiandan** [comment] 2018-04-26 16:16
+1

**Comment by kt3k** [comment] 2018-08-08 07:11
duplicate of #121

**Closed by kt3k** 2018-08-08 07:11 UTC
Labels: enhancement/feature request, new chart
