### ISSUE TITLE
Memory Leak IE11

### ISSUE THREAD

**Issue by phantomxc** [c3js/c3#1183] opened 2015-05-26 21:44 UTC
It appears that when minimizing the browser mid animation, IE 11 ( 11.0.9600.16428 and 11.0.9600.17691 ) doesn't stay happy. If you watch the task manager, the memory of the browser will slowly creep up and then start jumping up in larger increments. This will continue until the browser becomes unusable. You'll notice a significant jump in memory usage within 30 seconds. If not, you may have been a little slow minimizing the browser.

Example :
https://jsfiddle.net/1vb49uqc/1/

I was NOT able to reproduce this issue in the latest versions of Chrome, Safari, or Firefox.

**Comment by mrowa** [comment] 2015-06-03 11:03
I had similar issue with `flow` in Firefox, but after longer time of work. It looks like in Chrome and Firefox, where you're using `flow` when either different tab is open or window is minimized, the full flow is not done (which is ok). The problem is, that after few `flow`s while not rendering, all the elements are added at once, without removing enough elements from the beginning of the chart.

My guess is that all the SVG elements are created and thus are using up memory.

Example (updated @phantomxc's example with count of elements shown):
https://jsfiddle.net/du0qbfa0/1/

Open, check amount of elements under chart, switch tab / minimize browser, wait a minute, go back to tab with chart, compare the amount.

**Comment by panthony** [comment] 2018-03-31 11:08
closing in favor of #2057

**Closed by panthony** 2018-03-31 11:08 UTC
