### ISSUE TITLE
Event Rect Single does't support???

### ISSUE THREAD

**Issue by enesyteam** [c3js/c3#2548] opened 2018-12-11 19:41 UTC
Old version (0.4.x) support event rect single, but in 0.6.x I don't see this. I need to show tooltip on mouse over near to vertical gridline of POINT, show with Event Rect Multiple it does not work.
Please bring it back!

**Comment by panthony** [comment] 2019-08-16 14:13
I believe this is a duplicate of #2362

**Closed by panthony** 2019-08-16 14:13 UTC
