### ISSUE TITLE
Bar char drops an arbitrary data series when x value is falsy (null, undefined, empty string)

### ISSUE THREAD

**Issue by xinchao-zhang** [c3js/c3#2305] opened 2018-03-12 14:43 UTC
C3 version: 0.4.20
Browser: Chrome 4.0.3282.186 
OS: MacOS High Sierra 10.13.3

When using bar chart with Json data format, if one of the Json data object does not have the x attribute defined, the bar chart will arbitrarily drop a data series (the one missing the x value is actually rendered as having x-value "null")

Sample chart configuration:

    var chart = c3.generate({
        data: {
            json: [
                {name: 'data1',value: 200},
                {value: 100},
                {name: 'data3', value: 300},
                {name: 'data4', value: 400},
            ],

        keys: {
                x: 'name', 
                value: ['value'],
            },
            type: 'bar'
        },
        axis: {
            x: {
                type: 'category'
            }
        }
    });

![image](https://user-images.githubusercontent.com/36215332/37290287-380bdb6c-25e2-11e8-893a-5305d54743a1.png)

**Comment by panthony** [comment] 2018-03-24 07:33
Hi,

What would be the expected behavior? The row with the missing name would not be rendered at all?

I don't know if sanitizing the input data should be c3js responsability or not.

**Comment by xinchao-zhang** [comment] 2018-04-11 02:29
Sanitizing aside, I think the library should be consistent in its behavior: either ignore the problematic data series entirely, or render it properly with null/undefined as the x value.

If you look at the image, what happens now is that the problematic data series `{value: 100}` is actually rendered (as the middle bar), giving the illusion that C3 can handle falsy x values in the bar chart. However, **another arbitrary, good data series was dropped**, in my example above it was the `{name: 'data4', value: 400}`. It is just hard to relate the missing of data4 to the fact that there is another series missing its x value.

**Comment by panthony** [comment] 2018-04-11 06:07
@xinchao-zhang I didn't see that one of the valid series was discarded so in this regard there is clearly a bug.

For series with the missing 'x' maybe they should be discarded with a warning?

I'm just trying to figure out what could be a good/safe behavior for c3js so that if someone want to tackle of fix for this issue it is clear what should be done to fix it.

**Comment by xinchao-zhang** [comment] 2018-04-11 10:42
@panthony I think discarding the series with a warning or rendering with x label being `null' either way it is a reasonable contract. Ultimately this is still a data issue so people are unlikely to rely on the behavior as a feature. 

That being said, it seems there is no difficulty of showing the data series with x being null, and other types of charts work the same way without any issue (e.g. pie/donut charts handle all series fine even if one of them has x as null). I would suggest to do the same for bar chart?

**Comment by panthony** [comment] 2019-08-09 14:13
This is actually a duplicate of #2305.

When building the values for the category serie, all falsy values are filtered thus the indices between the category and the values does not correspond anymore.

**Closed by panthony** 2019-08-09 14:13 UTC
Labels: :bug: bug
